notifications:
  email: false

branches:
  only:
  - master

sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
  - mkdir _build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build constitution.tex
after_success:
  # Push the constitution to the website repo
  - .travis/push.sh

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "TravisCI"
  - export TRAVIS_TAG=build-$(date +'%Y-%m-%d')
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: _build/constitution.pdf
  skip_cleanup: true

